apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: argocd
resources:
  #https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - install.yaml


configMapGenerator:
  - name: argocd-cm
    files:
      - config/dex.config
      - config/url
    behavior: merge

  - name: argocd-rbac-cm
    files: 
      - config/policy.csv
    behavior: merge

patchesStrategicMerge:
- patch-argocd-insecure.yaml