apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: infra
spec:
  selector:
    matchLabels:
      app: whoami      
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - image: containous/whoami 
        name: whoami
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: infra
spec:
  selector:
    app: whoami
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  namespace: infra
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/preserve-host: "true"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - host: whoami.k8s.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami
            port: 
              number: 80
  tls:
    - hosts:
      - whoami.k8s.local
      secretName: traefik-tls-cert