apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      volumes:
        - name: config
          configMap:
            name: traefik-https-cfg
        - name: certs
          secret:
            secretName: traefik-tls-cert
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:v2.4.9
        name: traefik-ingress-lb
        ports:
        - name: http
          containerPort: 80
        - name: admin
          containerPort: 8080
        env:
        volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /certs
            name: certs
        args:
        - --api
        - --configfile=/config/traefik.toml
        - --providers.kubernetescrd
        - --set metrics.prometheus.enabled=true
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
spec:
  type: LoadBalancer
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 443
      name: https
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: admin
