apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

resources:
  - traefik_crd.yaml
  - traefik_rbac.yaml
  - default_tls_store.yaml
  - deployment.yaml
  
  
configMapGenerator:
  - name: traefik-https-cfg
    files:
      - traefik.toml

